### ISSUE TITLE
请问把play_radio.php上传我的伺服器，怎么播放啊？

### ISSUE THREAD

**Issue by goolguy007** [GoneToneStudio/php-hinet-hichannel-taiwan-radio#3]
请问以pop radio 为例，播放格式是这样吗：http://149.129.100.78/play_radio.php?id=RA000080
非常感谢！

**Comment by GoneTone** [comment]
範例程式碼：https://github.com/GoneToneStudio/php-hinet-hichannel-taiwan-radio/blob/master/examples/webpage/play_radio.php

只需要設定完整電台名稱就可，如果伺服器不是在台灣，需要在掛上台灣 Proxy。

**Comment by GoneTone** [comment]
這是實際運行的 Demo：https://demo.reh.tw/hichannel/

**Comment by goolguy007** [comment]
> 這是實際運行的 Demo：https://demo.reh.tw/hichannel/

非常感谢。但是大陆播放不了。不过我却根据您的思路，在pop radio官方app抓出一个串流地址，然后进行二次串流播放。这样，任何人都可以收听了。 P.S pop radio 官方app不限制ip。这是我二次串流的直链：http://149.129.100.78:8080/live/RA000080/hls.m3u8。非常感谢您的思路，就是同一ip播放。
